common:
  fp16: true
  log_format: json
  log_interval: 200
  seed: 1337
  tensorboard_logdir: tblog

checkpoint:
  save_interval_updates: 25000
  keep_interval_updates: 1
  no_epoch_checkpoints: true


distributed_training:
  ddp_backend: no_c10d
  distributed_backend: 'nccl'
  distributed_world_size: 32
  distributed_port: 29671
  nprocs_per_node: 8
  find_unused_parameters: true

task:
  _name: hubert_pretraining
  label_dir: /labels
  labels: "['km']"
  label_rate: ${model.label_rate}
  sample_rate: 16000
  max_sample_size: 250000
  min_sample_size: 32000
  pad_audio: false
  random_crop: true
  normalize: false # must be consistent with extractor

dataset:
  num_workers: 6
  max_tokens: 1400000
  skip_invalid_size_inputs_valid_test: true
  validate_interval: 5
  validate_interval_updates: 10000

criterion:
  _name: hubert
  pred_masked_weight: 1.0
  pred_nomask_weight: 0.0
  loss_weights: [10,]

optimizer:
  _name: adam
  adam_betas: [0.9,0.98]
  adam_eps: 1e-06
  weight_decay: 0.01
  max_update: 400000
  lr: [0.0005]
  clip_norm: 10.0

lr_scheduler:
  _name: polynomial_decay
  warmup_updates: 32000

model:
  _name: hubert
  label_rate: 100
  skip_masked: false
  skip_nomask: false
  mask_prob: 0.80
  extractor_mode: default
  conv_feature_layers: '[(512,10,5)] + [(512,3,2)] * 4 + [(512,2,2)] * 2'
  final_dim: 256
  num_classes: 500
  encoder_layerdrop: 0.05
  dropout_input: 0.1
  dropout_features: 0.1
  dropout: 0.1
  attention_dropout: 0.1
  feature_grad_mult: 0.1
  untie_final_proj: true
  activation_dropout: 0.0
  conv_bias: false
  apply_mask: true
  mask_selection: static
  mask_length: 10
  mask_other: 0
  mask_channel_selection: static
  mask_channel_length: 64
  mask_channel_other: 0
  mask_channel_prob: 0.5
  layerdrop: 0.1
  freeze_finetune_updates: 10000
  no_mask_overlap: false
  mask_min_space: 1
  no_mask_channel_overlap: false
  mask_channel_min_space: 1
  logit_temp: 0.1
  encoder_embed_dim: 768
  target_glu: false
  required_seq_len_multiple: 2
  pos_conv_depth: 5
  conv_pos: 95
  conv_pos_groups: 16
  conv_pos_batch_norm: false
  encoder_layers: 12
  layer_norm_first: false
  layer_type: 'transformer'
  checkpoint_activations: false
  encoder_ffn_embed_dim: 3072
  encoder_attention_heads: 12
  activation_fn: gelu
